site:
  title: Provisioning Integration Server
  url: https://docs.opennms.com
  start_page: pris::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
    tags: v*
    start_path: docs
ui:
  bundle:
    url: https://github.com/opennms-forge/antora-ui-opennms/releases/download/v3.1.0/ui-bundle.zip
asciidoc:
  attributes:
    stem: latexmath
output:
  clean: true
  dir: ./public
  destinations:
  - provider: fs
  - provider: archive
